Specify ruby-version 2.7.6 for tests workflow
The new GitHub [setup-ruby action, supervised by Ruby]
wants a Ruby version being fully specified

Thus, with our Ruby version set as 2.7.x
it raises the next error:

Error: Unknown version 2.7.x for ruby on ubuntu-22.04

[setup-ruby action, supervised by Ruby]:https://github.com/ruby/setup-ruby